name: "Tests"

on:
  pull_request:
    branches:         # array of glob patterns matching against refs/heads. Optional; defaults to all
      - master        # triggers on pulls to main
  push:
    branches:         # array of glob patterns matching against refs/heads. Optional; defaults to all
      - master        # triggers on pushes that contain changes in main

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 21.x, 22.x, 23.x]
    steps:
      - uses: actions/checkout@v4.2.2
        name: Checkout
      - uses: actions/setup-node@v4.1.0
        name: Setup Node.js ${{ matrix.node-version }} 
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Run npm ci
        run: npm ci
      - name: Run tests
        run: npm test
  Build:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        name: Checkout
      - uses: actions/setup-node@v4.1.0
        name: Setup Node.js
        with:
          node-version: 20.x
          cache: 'npm'
      - name: Run npm ci
        run: npm ci
      - name: Run build
        run: npm run build
      # - name: Run npm publish
      #   run: npm publish
      - name: Run npm pack
        run: npm pack
      - name: Archive build
        uses: actions/upload-artifact@v4.5.0 
        with:
          name: package
          path: '*.tgz'

  # Deploy:
  #   needs: Build
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #     - uses: actions/download-artifact@v4.1.8
  #       with:
  #         name: package
  #     - uses: actions/setup-node@v4.1.0
  #       name: Setup Node.js
  #       with:
  #         node-version: 20.x
  #         cache: 'npm'
  #     - name: Run npm ci
  #       run: npm ci
  #     - name: Run npm publish
  #       run: npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}